DROP TABLE IF EXISTS flights;

--CREATE TABLE 'FLIGHTS'

CREATE TABLE flights(
    YEAR INT,
    MONTH INT,
    DAY INT,
    DAY_OF_WEEK INT,
    AIRLINE VARCHAR(10),
    FLIGHT_NUMBER INT,
    TAIL_NUMBER VARCHAR(10),
    ORIGIN_AIRPORT VARCHAR(10),
    DESTINATION_AIRPORT VARCHAR(10),
    SCHEDULED_DEPARTURE INT,
    DEPARTURE_TIME INT,
    DEPARTURE_DELAY INT,
    TAXI_OUT INT,
    WHEELS_OFF INT,
    SCHEDULED_TIME INT,
    ELAPSED_TIME INT,
    AIR_TIME INT,
    DISTANCE INT,
    WHEELS_ON INT,
    TAXI_IN INT,
    SCHEDULED_ARRIVAL INT,
    ARRIVAL_TIME INT,
    ARRIVAL_DELAY INT,
    DIVERTED INT,
    CANCELLED INT,
    CANCELLATION_REASON VARCHAR(5),
    AIR_SYSTEM_DELAY INT,
    SECURITY_DELAY INT,
    AIRLINE_DELAY INT,
    LATE_AIRCRAFT_DELAY INT,
    WEATHER_DELAY INT
);

--CHECK THAT TABLE HAS BEEN CREATED 
SELECT *
FROM flights
LIMIT 10;

-- DROP UNECESSARY COLUMNS 
ALTER TABLE flights
	DROP COLUMN YEAR,
	DROP COLUMN WHEELS_ON,
	DROP COLUMN TAXI_IN,
	DROP COLUMN SCHEDULED_ARRIVAL,
	DROP COLUMN ARRIVAL_TIME,
	DROP COLUMN CANCELLATION_REASON,
	DROP COLUMN AIR_SYSTEM_DELAY, 
	DROP COLUMN SECURITY_DELAY,
	DROP COLUMN AIRLINE_DELAY,
	DROP COLUMN LATE_AIRCRAFT_DELAY,
	DROP COLUMN WEATHER_DELAY;

--CONFIRM TABLE HAS BEEN ALTERED 
SELECT *
FROM flights
LIMIT 10;

--LOOK AT AIRLINE VALUE COUNT 
SELECT AIRLINE, COUNT(*) as value_count
FROM flights
GROUP BY AIRLINE
ORDER BY value_count DESC;

DELETE FROM flights
WHERE AIRLINE NOT IN ('WN', 'DL', 'AA');

-- CONFIRM TABLE HAS BEEN ALTERED
SELECT *
FROM flights
LIMIT 10;

-- -- AIRLINE VALUE COUNT 
SELECT AIRLINE, COUNT(*) as value_count
FROM flights
GROUP BY AIRLINE
ORDER BY value_count DESC;

SELECT *
FROM flights;